package model;
// Generated 03.05.2018 23:28:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="nmudb"
)
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set<Pnz> pnzs = new HashSet<Pnz>(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(String cityName, Set<Pnz> pnzs) {
       this.cityName = cityName;
       this.pnzs = pnzs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="city_id", unique=true, nullable=false)
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    
    @Column(name="city_name", nullable=false, length=30)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Pnz> getPnzs() {
        return this.pnzs;
    }
    
    public void setPnzs(Set<Pnz> pnzs) {
        this.pnzs = pnzs;
    }




}


