package model;
// Generated 21.02.2018 13:40:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pnz generated by hbm2java
 */
public class Pnz  implements java.io.Serializable {


     private int pnzId;
     private String pnzName;
     private City city;
     private Set<PnzData> pnzDatas = new HashSet<PnzData>(0);

    /**
     *
     */
    public Pnz() {
    }

    /**
     *
     * @param pnzName
     */
    public Pnz(String pnzName) {
        this.pnzName = pnzName;
    }
	
    /**
     *
     * @param pnzId
     * @param city
     * @param pnzName
     */
    public Pnz(int pnzId, City city, String pnzName) {
        this.pnzId = pnzId;
        this.city=city;
        this.pnzName = pnzName;
    }
/**
     *
     * @param pnzId
     * @param pnzName
     */
    public Pnz(int pnzId, String pnzName) {
        this.pnzId = pnzId;
        this.pnzName = pnzName;
    }
    /**
     *
     * @param pnzId
     * @param city
     * @param pnzName
     * @param pnzDatas
     */
    public Pnz(int pnzId, City city, String pnzName, Set<PnzData> pnzDatas) {
       this.pnzId = pnzId;
       this.city = city;
       this.pnzName = pnzName;
       this.pnzDatas = pnzDatas;
    }
   
    /**
     *
     * @return
     */
    public int getPnzId() {
        return this.pnzId;
    }
    
    /**
     *
     * @param pnzId
     */
    public void setPnzId(int pnzId) {
        this.pnzId = pnzId;
    }
    
     /**
     *
     * @return
     */
    public City getCity() {
        return this.city;
    }
    
    /**
     *
     * @param city
     */
    public void setCity(City city) {
        this.city = city;
    }

    /**
     *
     * @return
     */
    public String getPnzName() {
        return this.pnzName;
    }
    
    /**
     *
     * @param pnzName
     */
    public void setPnzName(String pnzName) {
        this.pnzName = pnzName;
    }

    /**
     *
     * @return
     */
    public Set<PnzData> getPnzDatas() {
        return this.pnzDatas;
    }
    
    /**
     *
     * @param pnzDatas
     */
    public void setPnzDatas(Set<PnzData> pnzDatas) {
        this.pnzDatas = pnzDatas;
    }




}


