package model;
// Generated 21.02.2018 13:40:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PnzData generated by hbm2java
 */
public class PnzData  implements java.io.Serializable {


     private Integer pnzDataId;
     private Pnz pnz;
     private Date pnzDateTime;
     private double bsh;
     private double ds;
     private double sr;
     private double ou;
     private double do_;
     private double oa;
     private double ozon;
     private double serovodorod;
     private double fenol;
     private double fv;
     private double hlor;
     private double hv;
     private double ammiak;
     private double skIs;
     private double formaldigid;
     private double nsm;
     private double hromSh;
     private double sumU;

    /**
     *
     */
    public PnzData() {
    }
    
    /**
     *
     * @param bsh
     * @param ds
     * @param sr
     * @param ou
     * @param do_
     * @param oa
     * @param ozon
     * @param serovodorod
     * @param fenol
     * @param fv
     * @param hlor
     * @param hv
     * @param ammiak
     * @param skIs
     * @param formaldigid
     * @param nsm
     * @param hromSh
     * @param sumU
     */
    public PnzData(double bsh, double ds, double sr, double ou, double do_, double oa, double ozon, double serovodorod, double fenol, double fv, double hlor, double hv, double ammiak, double skIs, double formaldigid, double nsm, double hromSh, double sumU) {
       this.bsh = bsh;
       this.ds = ds;
       this.sr = sr;
       this.ou = ou;
       this.do_ = do_;
       this.oa = oa;
       this.ozon = ozon;
       this.serovodorod = serovodorod;
       this.fenol = fenol;
       this.fv = fv;
       this.hlor = hlor;
       this.hv = hv;
       this.ammiak = ammiak;
       this.skIs = skIs;
       this.formaldigid = formaldigid;
       this.nsm = nsm;
       this.hromSh = hromSh;
       this.sumU = sumU;
    }

    /**
     *
     * @param pnzDataId
     * @param pnz
     * @param pnzDateTime
     * @param bsh
     * @param ds
     * @param sr
     * @param ou
     * @param do_
     * @param oa
     * @param ozon
     * @param serovodorod
     * @param fenol
     * @param fv
     * @param hlor
     * @param hv
     * @param ammiak
     * @param skIs
     * @param formaldigid
     * @param nsm
     * @param hromSh
     * @param sumU
     */
    public PnzData(int pnzDataId, Pnz pnz, Date pnzDateTime, double bsh, double ds, double sr, double ou, double do_, double oa, double ozon, double serovodorod, double fenol, double fv, double hlor, double hv, double ammiak, double skIs, double formaldigid, double nsm, double hromSh, double sumU) {
       this.pnzDataId = pnzDataId;
       this.pnz = pnz;
       this.pnzDateTime = pnzDateTime;
       this.bsh = bsh;
       this.ds = ds;
       this.sr = sr;
       this.ou = ou;
       this.do_ = do_;
       this.oa = oa;
       this.ozon = ozon;
       this.serovodorod = serovodorod;
       this.fenol = fenol;
       this.fv = fv;
       this.hlor = hlor;
       this.hv = hv;
       this.ammiak = ammiak;
       this.skIs = skIs;
       this.formaldigid = formaldigid;
       this.nsm = nsm;
       this.hromSh = hromSh;
       this.sumU = sumU;
    }
   
    /**
     *
     * @param pnz
     * @param pnzDateTime
     * @param bsh
     * @param ds
     * @param sr
     * @param ou
     * @param do_
     * @param oa
     * @param ozon
     * @param serovodorod
     * @param fenol
     * @param fv
     * @param hlor
     * @param hv
     * @param ammiak
     * @param skIs
     * @param formaldigid
     * @param nsm
     * @param hromSh
     * @param sumU
     */
    public PnzData(Pnz pnz, Date pnzDateTime, double bsh, double ds, double sr, double ou, double do_, double oa, double ozon, double serovodorod, double fenol, double fv, double hlor, double hv, double ammiak, double skIs, double formaldigid, double nsm, double hromSh, double sumU) {
       this.pnz = pnz;
       this.pnzDateTime = pnzDateTime;
       this.bsh = bsh;
       this.ds = ds;
       this.sr = sr;
       this.ou = ou;
       this.do_ = do_;
       this.oa = oa;
       this.ozon = ozon;
       this.serovodorod = serovodorod;
       this.fenol = fenol;
       this.fv = fv;
       this.hlor = hlor;
       this.hv = hv;
       this.ammiak = ammiak;
       this.skIs = skIs;
       this.formaldigid = formaldigid;
       this.nsm = nsm;
       this.hromSh = hromSh;
       this.sumU = sumU;
    }
    
    /**
     *
     * @return
     */
    public Integer getPnzDataId() {
        return this.pnzDataId;
    }
    
    /**
     *
     * @param pnzDataId
     */
    public void setPnzDataId(Integer pnzDataId) {
        this.pnzDataId = pnzDataId;
    }

    /**
     *
     * @return
     */
    public Pnz getPnz() {
        return this.pnz;
    }
    
    /**
     *
     * @param pnz
     */
    public void setPnz(Pnz pnz) {
        this.pnz = pnz;
    }

    /**
     *
     * @return
     */
    public Date getPnzDateTime() {
        return this.pnzDateTime;
    }
    
    /**
     *
     * @param pnzDateTime
     */
    public void setPnzDateTime(Date pnzDateTime) {
        this.pnzDateTime = pnzDateTime;
    }

    /**
     *
     * @return
     */
    public double getBsh() {
        return this.bsh;
    }
    
    /**
     *
     * @param bsh
     */
    public void setBsh(double bsh) {
        this.bsh = bsh;
    }

    /**
     *
     * @return
     */
    public double getDs() {
        return this.ds;
    }
    
    /**
     *
     * @param ds
     */
    public void setDs(double ds) {
        this.ds = ds;
    }

    /**
     *
     * @return
     */
    public double getSr() {
        return this.sr;
    }
    
    /**
     *
     * @param sr
     */
    public void setSr(double sr) {
        this.sr = sr;
    }

    /**
     *
     * @return
     */
    public double getOu() {
        return this.ou;
    }
    
    /**
     *
     * @param ou
     */
    public void setOu(double ou) {
        this.ou = ou;
    }

    /**
     *
     * @return
     */
    public double getDo_() {
        return this.do_;
    }
    
    /**
     *
     * @param do_
     */
    public void setDo_(double do_) {
        this.do_ = do_;
    }

    /**
     *
     * @return
     */
    public double getOa() {
        return this.oa;
    }
    
    /**
     *
     * @param oa
     */
    public void setOa(double oa) {
        this.oa = oa;
    }

    /**
     *
     * @return
     */
    public double getOzon() {
        return this.ozon;
    }
    
    /**
     *
     * @param ozon
     */
    public void setOzon(double ozon) {
        this.ozon = ozon;
    }

    /**
     *
     * @return
     */
    public double getSerovodorod() {
        return this.serovodorod;
    }
    
    /**
     *
     * @param serovodorod
     */
    public void setSerovodorod(double serovodorod) {
        this.serovodorod = serovodorod;
    }

    /**
     *
     * @return
     */
    public double getFenol() {
        return this.fenol;
    }
    
    /**
     *
     * @param fenol
     */
    public void setFenol(double fenol) {
        this.fenol = fenol;
    }

    /**
     *
     * @return
     */
    public double getFv() {
        return this.fv;
    }
    
    /**
     *
     * @param fv
     */
    public void setFv(double fv) {
        this.fv = fv;
    }

    /**
     *
     * @return
     */
    public double getHlor() {
        return this.hlor;
    }
    
    /**
     *
     * @param hlor
     */
    public void setHlor(double hlor) {
        this.hlor = hlor;
    }

    /**
     *
     * @return
     */
    public double getHv() {
        return this.hv;
    }
    
    /**
     *
     * @param hv
     */
    public void setHv(double hv) {
        this.hv = hv;
    }

    /**
     *
     * @return
     */
    public double getAmmiak() {
        return this.ammiak;
    }
    
    /**
     *
     * @param ammiak
     */
    public void setAmmiak(double ammiak) {
        this.ammiak = ammiak;
    }

    /**
     *
     * @return
     */
    public double getSkIs() {
        return this.skIs;
    }
    
    /**
     *
     * @param skIs
     */
    public void setSkIs(double skIs) {
        this.skIs = skIs;
    }

    /**
     *
     * @return
     */
    public double getFormaldigid() {
        return this.formaldigid;
    }
    
    /**
     *
     * @param formaldigid
     */
    public void setFormaldigid(double formaldigid) {
        this.formaldigid = formaldigid;
    }

    /**
     *
     * @return
     */
    public double getNsm() {
        return this.nsm;
    }
    
    /**
     *
     * @param nsm
     */
    public void setNsm(double nsm) {
        this.nsm = nsm;
    }

    /**
     *
     * @return
     */
    public double getHromSh() {
        return this.hromSh;
    }
    
    /**
     *
     * @param hromSh
     */
    public void setHromSh(double hromSh) {
        this.hromSh = hromSh;
    }

    /**
     *
     * @return
     */
    public double getSumU() {
        return this.sumU;
    }
    
    /**
     *
     * @param sumU
     */
    public void setSumU(double sumU) {
        this.sumU = sumU;
    }




}


